/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chunyu_demotest_ndk_TestNdk */

#ifndef _Included_com_example_chunyu_demotest_ndk_TestNdk
#define _Included_com_example_chunyu_demotest_ndk_TestNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chunyu_demotest_ndk_TestNdk
 * Method:    getfriend
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chunyu_demotest_ndk_TestNdk_getfriend
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
