/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chunyu_demotest_ndk_NdkTest */

#ifndef _Included_com_example_chunyu_demotest_ndk_NdkTest
#define _Included_com_example_chunyu_demotest_ndk_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chunyu_demotest_ndk_NdkTest
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chunyu_demotest_ndk_NdkTest_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
